[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "astra"
version = "0.0.1"
description = "ASTRA"
authors = [
  { name = "Andreas Skov Millarch", email = "andreasmillarch@gmail.com" },
]

[project.optional-dependencies]
service = ["fastapi>=0.110", "uvicorn>=0.27", "httpx>=0.24"]


[tool.setuptools]
packages = ["astra"]