import logging
import os

import matplotlib
if __name__ == "__main__":
    matplotlib.use("Agg")  # headless backend for script execution only
import matplotlib.pyplot as plt
import pandas as pd

logger = logging.getLogger(__name__)


def plot_prediction_trajectory(result, ctx, save_path=None, model_name=None):
    """Plot P(deceased_30d) at each visible timestep.

    For temporal models, uses the per-timestep predictions from the forward pass.
    For non-temporal models, loads the evaluation preds_df CSV (generated by
    ``--comprehensive-eval``) and plots that patient's predictions over time.

    Args:
        result: InferenceResult from predict_from_context.
        ctx: PatientContext with pid, bin_df, admission_time.
        save_path: Path to save the figure (None = display only).
        model_name: Model name, used to locate preds_df CSV for non-temporal models.

    Returns:
        matplotlib.figure.Figure or None if data unavailable.
    """
    if result.predictions_over_time is not None:
        return _plot_temporal_trajectory(result, ctx, save_path)

    return _plot_nontemporal_trajectory(ctx, save_path, model_name)


def _plot_temporal_trajectory(result, ctx, save_path):
    """Plot trajectory from temporal head predictions (single forward pass)."""
    probs = result.predictions_over_time  # [seq_len]
    traj_len = result.trajectory_length

    # Bin midpoints as hours since admission
    bin_df = ctx.bin_df
    admission = ctx.admission_time
    hours = [
        (row.bin_start - admission).total_seconds() / 3600
        + (row.bin_end - row.bin_start).total_seconds() / 7200
        for _, row in bin_df.iterrows()
    ]
    hours = hours[:traj_len]
    probs_visible = probs[:traj_len]

    fig, ax = plt.subplots(figsize=(12, 4))
    ax.plot(hours, probs_visible, "o-", color="steelblue", markersize=3, linewidth=1.5)
    ax.axhline(0.5, color="gray", linestyle="--", alpha=0.5, label="0.5 threshold")
    ax.fill_between(hours, probs_visible, alpha=0.15, color="steelblue")

    ax.set_xlabel("Hours since admission")
    ax.set_ylabel("P(deceased 30d)")
    ax.set_title(f"Prediction trajectory — Patient {ctx.pid}")
    ax.set_ylim(-0.02, 1.02)
    ax.legend()
    ax.grid(True, alpha=0.3)

    return _finalize(fig, save_path)


def _plot_nontemporal_trajectory(ctx, save_path, model_name):
    """Plot trajectory from evaluation preds_df CSV (non-temporal model)."""
    if model_name is None:
        logger.warning("Non-temporal model and no model_name provided — "
                        "cannot load preds_df. Skipping trajectory plot.")
        return None

    csv_path = f'reports/predictions/preds_df_{model_name}.csv'
    if not os.path.exists(csv_path):
        logger.warning("preds_df not found at %s — run evaluation with "
                        "--comprehensive-eval first.", csv_path)
        return None

    preds_df = pd.read_csv(csv_path)

    # Map inference PID → cohort PID on-the-fly using historical base_df
    cohort_pid = None
    try:
        from astra.utils import get_base_df, make_inference_pid
        base = get_base_df()
        pid_map = {
            make_inference_pid(row.CPR_hash, row.ServiceDate): row.PID
            for _, row in base[['PID', 'CPR_hash', 'ServiceDate']].iterrows()
        }
        cohort_pid = pid_map.get(str(ctx.pid))
    except Exception:
        pass

    # Look up by resolved cohort PID, falling back to direct ctx.pid match
    if cohort_pid is not None:
        patient_df = preds_df[preds_df["PID"] == cohort_pid].sort_values("time_hours")
    else:
        patient_df = preds_df[preds_df["PID"] == ctx.pid].sort_values("time_hours")
        if patient_df.empty:
            patient_df = preds_df[preds_df["PID"].astype(str) == str(ctx.pid)].sort_values("time_hours")

    if patient_df.empty:
        logger.warning("Patient %s not found in preds_df (%s). "
                        "Patient may not be in the holdout set.", ctx.pid, csv_path)
        return None

    # Only show predictions within the patient's actual trajectory
    traj_hours = ctx.trajectory_length  # in bins, not hours
    admission = ctx.admission_time
    bin_df = ctx.bin_df
    max_hours = (
        (bin_df.iloc[min(ctx.trajectory_length, len(bin_df)) - 1].bin_end - admission)
        .total_seconds() / 3600
    )
    patient_df = patient_df[patient_df["time_hours"] <= max_hours]

    hours = patient_df["time_hours"].values
    probs = patient_df["pred"].values

    fig, ax = plt.subplots(figsize=(12, 4))
    ax.plot(hours, probs, "o-", color="steelblue", markersize=3, linewidth=1.5)
    ax.axhline(0.5, color="gray", linestyle="--", alpha=0.5, label="0.5 threshold")
    ax.fill_between(hours, probs, alpha=0.15, color="steelblue")

    ax.set_xlabel("Hours since admission")
    ax.set_ylabel("P(deceased 30d)")
    ax.set_title(f"Prediction trajectory — Patient {ctx.pid}")
    ax.set_ylim(-0.02, 1.02)
    ax.legend()
    ax.grid(True, alpha=0.3)

    return _finalize(fig, save_path)


def _finalize(fig, save_path):
    """Save and/or show figure, then return it."""
    plt.tight_layout()
    if save_path:
        os.makedirs(os.path.dirname(save_path), exist_ok=True)
        fig.savefig(save_path, dpi=150, bbox_inches="tight")
        logger.info("Saved trajectory plot to %s", save_path)
    plt.show()
    return fig
