import logging
import os

import numpy as np
import matplotlib
if __name__ == "__main__":
    matplotlib.use("Agg")  # headless backend for script execution only
import matplotlib.pyplot as plt
import pandas as pd

logger = logging.getLogger(__name__)


def _get_inhospital_start_hours(ctx):
    """Return hours since admission_time for inhospital start, or None.

    Returns None if hospital arrival has not yet occurred relative to
    ctx.current_time (prevents future information leakage in simulation).
    """
    ihs = ctx.demographics.get('inhospital_start')
    if ihs is None or (isinstance(ihs, float) and np.isnan(ihs)):
        return None
    ihs = pd.Timestamp(ihs)
    if pd.isna(ihs):
        return None
    # Don't reveal future events in simulation mode
    if hasattr(ctx, 'current_time') and ctx.current_time is not None:
        if ihs > ctx.current_time:
            return None
    hours = (ihs - ctx.admission_time).total_seconds() / 3600
    # Only meaningful if prehospital data pushes admission_time earlier
    return hours if hours > 0 else None


def _draw_inhospital_boundary_hours(ax, ihs_hours):
    """Draw a vertical line marking hospital arrival on an hours-based axis."""
    if ihs_hours is None:
        return
    ax.axvline(x=ihs_hours, color='#2196F3', linewidth=1.5, linestyle=':',
               alpha=0.8, label=f'Hospital arrival ({ihs_hours:.1f}h)')


def plot_prediction_trajectory(result, ctx, save_path=None, model_name=None):
    """Plot P(deceased_30d) at each visible timestep.

    For temporal models, uses the per-timestep predictions from the forward pass.
    For non-temporal models, loads the evaluation preds_df CSV (generated by
    ``--comprehensive-eval``) and plots that patient's predictions over time.

    Args:
        result: InferenceResult from predict_from_context.
        ctx: PatientContext with pid, bin_df, admission_time.
        save_path: Path to save the figure (None = display only).
        model_name: Model name, used to locate preds_df CSV for non-temporal models.

    Returns:
        matplotlib.figure.Figure or None if data unavailable.
    """
    if result.predictions_over_time is not None:
        return _plot_temporal_trajectory(result, ctx, save_path)

    return _plot_nontemporal_trajectory(ctx, save_path, model_name)


def _plot_temporal_trajectory(result, ctx, save_path):
    """Plot trajectory from temporal head predictions (single forward pass)."""
    probs = result.predictions_over_time  # [seq_len]
    traj_len = result.trajectory_length

    # Bin midpoints as hours since admission
    bin_df = ctx.bin_df
    admission = ctx.admission_time
    hours = [
        (row.bin_start - admission).total_seconds() / 3600
        + (row.bin_end - row.bin_start).total_seconds() / 7200
        for _, row in bin_df.iterrows()
    ]
    hours = hours[:traj_len]
    probs_visible = probs[:traj_len]

    # Filter NaN entries (bins not yet predicted, e.g. from simulation curves)
    mask = ~np.isnan(probs_visible)
    hours = [h for h, m in zip(hours, mask) if m]
    probs_visible = probs_visible[mask]

    fig, ax = plt.subplots(figsize=(12, 4))
    ax.plot(hours, probs_visible, "o-", color="steelblue", markersize=3, linewidth=1.5)
    ax.axhline(0.5, color="gray", linestyle="--", alpha=0.5, label="0.5 threshold")
    ax.fill_between(hours, probs_visible, alpha=0.15, color="steelblue")

    _draw_inhospital_boundary_hours(ax, _get_inhospital_start_hours(ctx))

    ax.set_xlabel("Hours since admission")
    ax.set_ylabel("P(deceased 30d)")
    ax.set_title(f"Prediction trajectory — Patient {ctx.pid}")
    ax.set_ylim(-0.02, 1.02)
    ax.legend()
    ax.grid(True, alpha=0.3)

    return _finalize(fig, save_path)


def _plot_nontemporal_trajectory(ctx, save_path, model_name):
    """Plot trajectory from evaluation preds_df CSV (non-temporal model)."""
    if model_name is None:
        logger.warning("Non-temporal model and no model_name provided — "
                        "cannot load preds_df. Skipping trajectory plot.")
        return None

    csv_path = f'reports/predictions/preds_df_{model_name}.csv'
    if not os.path.exists(csv_path):
        logger.warning("preds_df not found at %s — run evaluation with "
                        "--comprehensive-eval first.", csv_path)
        return None

    preds_df = pd.read_csv(csv_path)

    # Map inference PID → cohort PID on-the-fly using historical base_df
    cohort_pid = None
    try:
        from astra.utils import get_base_df, make_inference_pid
        base = get_base_df()
        pid_map = {
            make_inference_pid(row.CPR_hash, row.ServiceDate): row.PID
            for _, row in base[['PID', 'CPR_hash', 'ServiceDate']].iterrows()
        }
        cohort_pid = pid_map.get(str(ctx.pid))
    except Exception:
        logger.debug("Could not map inference PID to cohort PID; falling back to direct PID match")

    # Look up by resolved cohort PID, falling back to direct ctx.pid match
    if cohort_pid is not None:
        patient_df = preds_df[preds_df["PID"] == cohort_pid].sort_values("time_hours")
    else:
        patient_df = preds_df[preds_df["PID"] == ctx.pid].sort_values("time_hours")
        if patient_df.empty:
            patient_df = preds_df[preds_df["PID"].astype(str) == str(ctx.pid)].sort_values("time_hours")

    if patient_df.empty:
        logger.warning("Patient %s not found in preds_df (%s). "
                        "Patient may not be in the holdout set.", ctx.pid, csv_path)
        return None

    # Only show predictions within the patient's actual trajectory
    traj_hours = ctx.trajectory_length  # in bins, not hours
    admission = ctx.admission_time
    bin_df = ctx.bin_df
    max_hours = (
        (bin_df.iloc[min(ctx.trajectory_length, len(bin_df)) - 1].bin_end - admission)
        .total_seconds() / 3600
    )
    patient_df = patient_df[patient_df["time_hours"] <= max_hours]

    hours = patient_df["time_hours"].values
    probs = patient_df["pred"].values

    fig, ax = plt.subplots(figsize=(12, 4))
    ax.plot(hours, probs, "o-", color="steelblue", markersize=3, linewidth=1.5)
    ax.axhline(0.5, color="gray", linestyle="--", alpha=0.5, label="0.5 threshold")
    ax.fill_between(hours, probs, alpha=0.15, color="steelblue")

    _draw_inhospital_boundary_hours(ax, _get_inhospital_start_hours(ctx))

    ax.set_xlabel("Hours since admission")
    ax.set_ylabel("P(deceased 30d)")
    ax.set_title(f"Prediction trajectory — Patient {ctx.pid}")
    ax.set_ylim(-0.02, 1.02)
    ax.legend()
    ax.grid(True, alpha=0.3)

    return _finalize(fig, save_path)


def _finalize(fig, save_path):
    """Save and/or show figure, then return it."""
    plt.tight_layout()
    if save_path:
        os.makedirs(os.path.dirname(save_path), exist_ok=True)
        fig.savefig(save_path, dpi=150, bbox_inches="tight")
        logger.info("Saved trajectory plot to %s", save_path)
    plt.show()
    return fig


def default_session_plot(session, prediction_curve=None, interactive=False):
    """Render the standard inspection plots for ``session.ctx``.

    Used interactively (notebooks, ``SimulationRunner.inspect``) after a
    session has a context attached: prediction trajectory, individual SHAP
    panel and data completeness.

    Args:
        session: An :class:`~astra.inference.pipeline.InferenceSession` with
            ``session.ctx`` set (e.g. by ``SimulationRunner.setup``).
        prediction_curve: Optional simulation curve ``[seq_len]`` — lets
            non-temporal models show per-timestep predictions without a
            pre-computed evaluation CSV.
        interactive: Use the interactive plotly SHAP panels (plus EBM
            explanations when available) instead of matplotlib.
    """
    from astra.evaluation.behavior import (
        visualize_shap_individual,
        visualize_shap_individual_interactive,
        visualize_data_completeness,
    )
    from astra.evaluation.utils import time_to_step

    ctx = session.ctx
    result = session.predict_from_context(ctx)

    # If a simulation prediction curve is available, use it for trajectory
    # plotting (enables non-temporal models to show per-timestep predictions
    # from the simulation step-through without needing a pre-computed CSV).
    if prediction_curve is not None and result.predictions_over_time is None:
        from astra.inference.pipeline import InferenceResult
        plot_result = InferenceResult(
            pid=result.pid,
            probability=result.probability,
            trajectory_length=result.trajectory_length,
            censor_step=result.censor_step,
            predictions_over_time=prediction_curve,
        )
    else:
        plot_result = result

    plot_prediction_trajectory(
        plot_result, ctx,
        save_path=None,
        model_name=session.bundle.get('model_name'),
    )

    logger.info("Computing SHAP explanation...")
    shap_result = session.explain_from_context(ctx)

    shap_dict, channel2feature, feature_names_cat, feature_names_cont = (
        session.shap_to_viz_dict(
            shap_result,
            x_ts=ctx.x_ts,
            x_ts_cat=ctx.x_ts_cat,
            tab_df=ctx.tab_df,
        )
    )

    # Inject inhospital boundary info for SHAP plots (prehospital patients)
    ihs_time = ctx.demographics.get('inhospital_start')
    if ihs_time is not None:
        ihs_ts = pd.Timestamp(ihs_time)
        if pd.notna(ihs_ts):
            delta_min = (ihs_ts - ctx.admission_time).total_seconds() / 60
            ihs_step = time_to_step(
                delta_min, 'min',
                data_config=session.bundle.get('data_config'),
            )
            if ihs_step is not None:
                shap_dict['test_data']['inhospital_start_steps'] = np.array([ihs_step])

    if interactive:
        ebm_explanations = None
        if '_ebm_pred' in session.bundle.get('ts_channel_names', []):
            logger.info("Computing EBM feature importance...")
            ebm_explanations = session.explain_ebm(ctx, save_path=None)

        visualize_shap_individual_interactive(
            shap_dict,
            sample_idx=0,
            channel2feature=channel2feature,
            feature_names_cat=feature_names_cat,
            feature_names_cont=feature_names_cont,
            ebm_explanations=ebm_explanations,
        )
    else:
        visualize_shap_individual(
            shap_dict,
            sample_idx=0,
            channel2feature=channel2feature,
            feature_names_cat=feature_names_cat,
            feature_names_cont=feature_names_cont,
        )

    visualize_data_completeness(
        shap_dict,
        channel2feature=channel2feature,
        save_path=None,
    )
